application:
  name: "Complex App"
  version: 2.3
  maintenance: false
  servers:
    - id: server1
      description: "Primary server"
      ip: "192.168.1.1"
      roles:
        - web
        - api
    - id: server2
      description: "Backup server"
      ip: "192.168.1.2"
      roles:
        - db
logging:
  level: "INFO"
  path: "/var/log/complexapp.log"
  rotate: true
  maxFileSize: "10MB"
